### PR TITLE
updates to userProfile.php, UserChild.php and main.js

### PR DESCRIPTION
**Pull request by FrancescoWard**
Hi Team,
I hope this finds you well.
Please answer: how do we connect userProfile to the rest of the site ?
Thanks,
Francesco

### CODE REVIEW

**Comment by mcontado** [comment]
Francesco, can you please add the missing points here? I think it can't be updated to the db yet, am I correct?

**Comment by mcontado** [comment]
We can connect the userProfile once the session is set for the user

**Review by cjshaw — APPROVED** [review]
approving to merge when maria approves that change.

**Review by mcontado — APPROVED** [review]

**Comment by FrancescoWard** [comment]
Hi Maria,
Thanks for reviewing.
WRT "Francesco, can you please add the missing points here? I think it can't be updated to the db yet, am I correct?"
- When running the userProfile page following a login, if MAMP is enabled, the DB is updated via the existing updateUserProfile() function. Sure, the page only works with my dummy login page preceding it for now, I just need to know where to launch this userProfile page from and can then make minor changes to receive the correct _SESSION token.
Thanks,
Francesco

**Pull request merged**
