### PR TITLE
CSS changes pushed to CSS as of 06/01/2018 for review

### PR DESCRIPTION
**Pull request by gshields5541**
1. Added a “Search Events button in each slide of the carousel.
2. Added text and image animation effects.
3. Reverted the carousel to “Jumbotron” mode to encompass the main page.
4. “Recycled” the avatar image that was in the original login modal page to be included in registration.php, and login.php

### CODE REVIEW

**Comment by cjshaw** [comment]
Gerald, add either me or Mikal AND Maria to review this pull request.

**Review by mcontado — CHANGES_REQUESTED** [review]
- [ ] Remove the Search Events button on the top right of the nav bar.
- [ ] Search Events button not readable when hovering, please fix it.

**Comment by mcontado** [comment]
"Search Events" not readable when hovering:

image

**Comment by gshields5541** [comment]
.btn-transparent:hover {
    background-color: #2D6077 !important;
}
I set this setting previously set at #F1F1F1 when the cursor is over it.

Gerald

**Comment by gshields5541** [comment]
My Bad :)

Gerald

**Comment by gshields5541** [comment]
I’ve sent a commit with the changes you’ve outlined.

**Comment by mcontado** [comment]
Please resolve conflicts

**Comment by gshields5541** [comment]
@mcontado That last conflict with header.php ? Please check that one. I think I've avoided messing with the extra php code, but why is it in the middle of the html  rather than above or below it?

**Comment by mcontado** [comment]
@gshields5541 : I think bec Mekone added the authentication if the user is logged in or not. so you should remove the extra one above.

The `header.php` should be like this:

```
<div class="container-fluid">
    <nav class="navbar fixed-top navbar-expand-sm bg-light justify-content-end">
        <a class="navbar-brand" href="?controller=static&action=landing"><img src="views/images/Fun_LogoBanner.png" alt="Logo" class="logo-banner"></a>
        <ul class="navbar-nav">
            <?php
            // Initialize the session
            session_start();
            //3.1.4 if the user is logged in Greets the user with message
            if (isset($_SESSION['emailAddress'])) {
                echo '<li class="nav-item"><a class="nav-link" href="?controller=static&action=profile">Profile</a></li>';
                echo '<li class="nav-item"><a class="nav-link" href="?controller=static&action=logout">Logout</a></li>';
            } else {
                //3.2 When the user visits the page first time, simple login form will be displayed.
                echo '<li class="nav-item"><a class="nav-link" href="?controller=static&action=registration">Sign Up</a></li>';
                echo '<li class="nav-item"><a class="nav-link" href="?controller=static&action=login">Login</a></li>';
            }
            ?>
        </ul>
    </nav>
</div>

**Comment by gshields5541** [comment]
@mcontado I have a problem: I've already merged the conflict, so what I've sent is wrong.

**Review by mcontado — APPROVED** [review]

**Review by mviencek — APPROVED** [review]
The code looks good but search events is hard to see on two out of the three slides.  Also this is just my personal preference but I think you are over animated. I'll approve and merge

**Comment by gshields5541** [comment]
There was some changes I’ve made to make the Search Events button more visible. Can I get another confirmation on the issues you’ve mentioned?

Gerald

**Pull request merged**
