### PR TITLE
Search page

### PR DESCRIPTION
**Pull request by HjLubas**
FrontEnd Search Page - Maria Contado (lead)

### CODE REVIEW

**Review by mcontado — COMMENTED** [review]
can you please add those files under .idea into .gitignore. It's a little bit weird that these files are not being ignored, even though we specify the .idea/*

**Review by mviencek — CHANGES_REQUESTED** [review]
gitignore for .idea files.  unclosed div at line 44 of searchpage.  title missing from the head.

**Review by cjshaw — CHANGES_REQUESTED** [review]
See what Mikal's comment

**Comment by mcontado** [comment]
Why did you close this pull request?

**Comment by mviencek** [comment]
They can just resubmit a pull request after making the requested changes

**Comment by mcontado** [comment]
I agree, but I think we can still use the same Pull Request to update their changes, so that they can just push from their local and this will be automatically updated. And there is no need to create a new pull request again. (just an opinion)

**Pull request closed without merging**
