### PR TITLE
Updated the registration page to add user roles

### PR DESCRIPTION
**Pull request by mcontado**

### CODE REVIEW

**Comment by mviencek** [comment]
your roles look good but I have there is no styling on your page anymore.  is this still a work in progress?

**Comment by mviencek** [comment]
there is no styling on your page anymore.  was this intentional?  it doesnt look like its coming through on layout.php

**Review by cjshaw — APPROVED** [review]

**Review by mviencek — APPROVED** [review]
looks good.  although it looks like the the styling and header and footer aren't coming through ryans layout.  something to look at

**Comment by mcontado** [comment]
Hi @mviencek, there is an open issue, https://github.com/ad410project/ad410project/issues/46 that will update the controller to hook up the pages including the registration page. With that update, the header and footer will be coming through the layout.

**Pull request merged**
