### PR TITLE
fixed carousel

### PR DESCRIPTION
**Pull request by RohitSarwate**

### CODE REVIEW

**Comment by gshields5541** [comment]
I've been having problems with the carousel. I got it to work, but I've broken a "Search Events" link on the layout page and I've haven't been able to get it work just yet.

**Comment by RohitSarwate** [comment]
The link works for me. It takes me to the page where we have a map and search bar at the bottom.

**Comment by mviencek** [comment]
Are you in our class?  Your name is not familiar

**Comment by gshields5541** [comment]
Yes, I think.

**Comment by RohitSarwate** [comment]
No, I am not. You posted a question on StackOverflow and I was just trying to solve that.

**Comment by mviencek** [comment]
gotcha.  one of the contributors must have asked you a question.

**Comment by RohitSarwate** [comment]
Yes, I think it was Gerald who posted a question on StackOverflow.

**Comment by gshields5541** [comment]
Rohit:

I’m sorry. I’m the guy that asked for help. My bad. I think I solved the issue. Thank you for helping me though.

**Comment by RohitSarwate** [comment]
You are welcome !!

**Pull request closed without merging**
