### PR TITLE
Integration Search Events

### PR DESCRIPTION
**Pull request by mcontado**
Changes made:
- Connect the search events button to search events page
- Rename organization_events to user_events since this is general as a user not just by org.
- Change the input type to textarea for the description of events in addEvent and editEvent
- Added events_by_date and events_by_distance, search_events_public code by Harry
- Fix the carousel issue for user_events (former organization_events).

### CODE REVIEW

**Review by ad410project — COMMENTED** [review]
maria how does one navigate to events by date or events by distance?

**Review by ad410project — COMMENTED** [review]
i dont see either in the route or controller

**Comment by mcontado** [comment]
In the dynamic_controller.php, it changed to search_events_public.php, in the routes.php it was there already. (searcEvents). The search_events_public.php calls either events_by_distance or events_by_date.

**Review by mviencek — APPROVED** [review]
great work.

**Review by cjshaw — APPROVED** [review]

**Pull request merged**
