### PR TITLE
A number of Changes I've made to the CSS styling:

### PR DESCRIPTION
**Pull request by gshields5541**
1. Added Google Font "Open Sans" to layout.php
2. Added some text shadow effects to styles.css
3. Created org-carousel.css and embedded stylescript line in organizational events as a temporary solution to the CSS conflicts being the carousel in landing.php and the carousel in organization_events.php
4. Adjusted the javascripting added in main.js to support the Bootstrap Multi-Card Carousel in organization_events.php
(See: https://codepen.io/kreigd/pen/ybYNoN for details)
5. Adjusted the styling with terms.php and contact.php.
6. Added a "font awesome" calendar icon to the "Add Events" button in organization_events.php

### CODE REVIEW

**Comment by ad410project** [comment]
your fixed footer is cutting off the bottom part of the terms page.  try using sticky header and footers.  your footer also cuts off part of the search events button.  Get rid of the la, chicago, new york stuff.  We don't need it there anymore

**Comment by gshields5541** [comment]
It’s not cut off. You can scroll the document to the end of the page.

Gerald

**Comment by ad410project** [comment]
mypic

**Comment by ad410project** [comment]
half of the text is cut off on the last line.  part of the search events button is cut off too

**Comment by gshields5541** [comment]
Can I get a screenshot of what you’re seeing?

Gerald

**Comment by ad410project** [comment]
I already posted one.  Please see above

**Comment by ad410project** [comment]
the search events button should be above the fold and not partially obscured by the fixed footer too

**Comment by gshields5541** [comment]
That’s that terms page. I need to see the landing page.

Gerald

**Comment by ad410project** [comment]
pic_2

**Comment by ad410project** [comment]
I shouldnt have to scroll down to see the whole button

**Comment by ad410project** [comment]
Also if you look at the page on a mobile device or smaller window, the carousel needs work

**Comment by ad410project** [comment]
pic_3

**Comment by gshields5541** [comment]
I’ve told Maria I can’t test on a mobile device. There’s no emulators TIKF that would work with phpStorm

Gerald

**Comment by gshields5541** [comment]
What browser are you using? I’ve testing this page on 4 different browsers

Gerald

**Comment by ad410project** [comment]
http://54.201.248.112

**Comment by ad410project** [comment]
collapse your browser window and play with the size.  it will emulate what happens on a mobile device.

**Comment by ad410project** [comment]
im using chrome and firefox developers edition

**Comment by ad410project** [comment]
pic_4

**Comment by ad410project** [comment]
f12 click on mobile icon.  in chrome you can emulate a phone or a tablet

**Comment by ad410project** [comment]
pic_5

**Comment by gshields5541** [comment]
That’s nice, but the website wasn’t designed for mobile devices. AFAIK, neither the team nor Luv ever talked about adapting the website for mobile and we don’t really have much time before the end of the quarter. The bootstrap carousel as an example was only setup for a specific width and height , thus we would have to consider placing extra text in column to make up for all of that white-space. We’ve designed it as a landing page with one link. In the case of the use of terms page, it’s set up so that the user can scroll to the bottom of the page thus, it’s not “cut off” as you say. Just by changing the div page class on that page from container to container-fluid resolves it.

**Comment by mviencek** [comment]
I get that making the carousel look good on a mobile device wasnt part of the scope, I was just pointing it out.  The two requests I did have were adjusting the terms so the last line isnt partially cut of( i sent you a screenshot of what I'm seeing) and getting rid of the city/pizza/crowded stuff from the carousel.

**Review by cjshaw — COMMENTED** [review]
if you could fix the footer so it doesn't cover up text on the terms page and change the text on the carousel to be camp related that would be great.  
I'm going to approve and let maria take a look.

**Comment by mcontado** [comment]
I have made a couple of small changes like to add spacing at the bottom of the page, because we cant see/read the bottom of each page. Removing unneccesary items like static text about chicago,new york,etc, removed login button at the bottom of registration page since we already have it at the top.

**Review by mcontado — APPROVED** [review]

**Review by mviencek — APPROVED** [review]
Thank you for making the changes

**Pull request merged**
