### PR TITLE
Connecting pages in front end MVC

### PR DESCRIPTION
**Pull request by ryanybrennan**
Connected search_events.php, registration.php, and login modal to the template. 
Front End Team lead: Maria Contado
Front End Team member: Ryan Brennan

### CODE REVIEW

**Review by cjshaw — APPROVED** [review]
Looks good.

**Review by mcontado — APPROVED** [review]
Looks good. Except for the search events page, looks like it is not showing the list tab and calendar tabs. But we can address it later.

**Comment by mviencek** [comment]
the home view isn't hooked up in the static controller.  was this intentional?

**Comment by mviencek** [comment]
also you still have the pages folder in your project from the original commit.  is this intentional?

**Comment by ryanybrennan** [comment]
The home page isn't hooked up to the static controller because it won't be a static page. It will require data from the database, and logic from sign up and login to navigate to it. I meant to move it to a new folder, but forgot. Also, that's odd the pages folder still shows up on github, since I do not see it in my local project...

**Pull request merged**
