### PR TITLE
user.php file

### PR DESCRIPTION
**Pull request by yahya09206**

### CODE REVIEW

**Comment by mviencek** [comment]
Why are some of these functions static?  Wouldn't these be called after a user has been instantiated?
And getuserbyid() doesnt have a where clause for an id

**Comment by yahya09206** [comment]
would it be better to make the functions in the user class non static?

**Comment by mviencek** [comment]
i was just curious. if you are going to call them outside a instantiated class im ok with it.  also for your getuserbyid() or deleteuser() why do you need other variables than userid?  currently your getuserbyid() returns all users

**Review by mviencek — CHANGES_REQUESTED** [review]
please make your methods non static.  you need user information in order to call them.  also you are passing in all the users information to the delete and get functions.  you only need a users id and maybe one more if you want to be super safe.  also getuserbyid returns all users.

**Review by cjshaw — CHANGES_REQUESTED** [review]
refer to mike's comments on what to review.

**Pull request closed without merging**
