### PR TITLE
Sign up

### PR DESCRIPTION
**Pull request by gshields5541**
This is a mockup of the sign Up page I've setup.

### CODE REVIEW

**Comment by ad410project** [comment]
add gitignore to your .idea

**Comment by ad410project** [comment]
you also conflict with index.php please do a pull from development and resolve the conflict and resubmit your pull request

**Review by mviencek — APPROVED** [review]
change file signUp to signup.  web deb is usually lower case not camel

**Review by mcontado — CHANGES_REQUESTED** [review]
add all the .idea files under gitignore. 
please resolve conflicts

**Comment by mviencek** [comment]
please pull a recent copy of development and perform a merge before you resubmit.  that is what caused your path errors.

**Pull request closed without merging**
