### PR TITLE
init commit for userProfile page

### PR DESCRIPTION
**Pull request by FrancescoWard**
Hello Team,
I hope this finds you well.
Please see new branch "userProfile" for review.
Functionality is not yet 100% but will keep working on it.
Thank you.
Best regards,
Francesco

### CODE REVIEW

**Comment by cjshaw** [comment]
can you resubmit and assign your team lead and mikal or I?

**Comment by FrancescoWard** [comment]
Hi Clint,
Sure, please see new assignees.
Thanks,
Francesco

**Review by mcontado — APPROVED** [review]
Please add necessary fields needed as you progress. We might change the adding of child to not just add up to 5 only.

**Review by cjshaw — APPROVED** [review]
number of children should probably be unlimited but i'm going to approve as other things aren't quite set anyway.

**Pull request merged**
