### PR TITLE
Organization

### PR DESCRIPTION
**Pull request by mcontado**
- Added organization page when the user is an org.
- Updated the controller
- Added editEvent.php and addEvent.php (not saving to the db yet) - needed db and backend work.

In order to view this, go to: http://localhost/?controller=dynamic&action=organization_events

Remaining tasks:
- Action when adding event to the db
- Action when editing event
- Action when adding events from api carousel into db.
- Routing of this controller once the user is logged in as an organization.

### CODE REVIEW

**Review by mviencek — APPROVED** [review]
quality code.  great job

**Comment by mviencek** [comment]
Just a nitpick.  Links for events should open up in another tab.  You dont want the user to navigate away from your site if you can help it

line 74-81 organization_events.php

**Review by mviencek — CHANGES_REQUESTED** [review]
please adjust media query.  it broke geralds carousel.

**Comment by mcontado** [comment]
I was not able to figure this out. May need some help with that. It looks like it overrides other media query.

**Comment by mviencek** [comment]
Im not sure whats going on with it either.  I would consider applying ids to the carousel divs and only having that query apply to those particular ids

**Comment by mcontado** [comment]
I dont think if it's on carousel issue, but it looks like that the `@media (min-width: 768px)` is overriding gerald's media query.

**Comment by gshields5541** [comment]
The carousel itself has an Id. Though the divs in the carousel don’t have ids, they are noted by class.

Gerald

**Comment by gshields5541** [comment]
Er, the carousel div itself has an id, I mean.

Gerald

**Review by mviencek — APPROVED** [review]

**Comment by mviencek** [comment]
updated your routes with info from ryans branch

**Review by cjshaw — APPROVED** [review]

**Pull request merged**
